### ISSUE TITLE
Cannot run scalatest from intellij

### ISSUE THREAD

**Issue by sauravshah** [JetBrains/intellij-sbt#3]
I imported a sbt project using the plugin and tried to run a test. This is the error I get

Unable to load a Suite class. This could be due to an error in your runpath. Missing class: scaldi.IdentifierSpec
java.lang.ClassNotFoundException: scaldi.IdentifierSpec
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at org.scalatest.tools.Runner$$anonfun$21.apply(Runner.scala:1470)
    at org.scalatest.tools.Runner$$anonfun$21.apply(Runner.scala:1469)
    at scala.collection.TraversableLike$$anonfun$filter$1.apply(TraversableLike.scala:264)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.filter(TraversableLike.scala:263)
    at scala.collection.AbstractTraversable.filter(Traversable.scala:105)
    at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1469)
    at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:705)
    at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:704)
    at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1645)
    at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:703)
    at org.scalatest.tools.Runner$.run(Runner.scala:592)
    at org.scalatest.tools.Runner.run(Runner.scala)
    at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest1(ScalaTestRunner.java:213)
    at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:37)

**Comment by manonthegithub** [comment]
I have the similar issue
